#!/bin/sh
# run dmas straight from the checkout without installing
exec python3 -c "import sys, os; sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath('$0')), 'src')); from deductive_mas.cli.main import main; sys.exit(main())" "$@"
